"""Local filesystem document storage.

Security guarantees:
- The storage root is resolved to an absolute path at construction time.
- Every stored file path is constructed from ``storage_root / <document_id><ext>``
  where ``document_id`` is a UUID generated by the service — clients never
  influence the stored path.
- ``safe_delete`` confirms the resolved path is still inside the storage root
  before removal, preventing any theoretical traversal via symlinks.
- The original filename is NEVER used as a filesystem path component.
"""

from __future__ import annotations

import re
import unicodedata
from pathlib import Path

from app.core.logging import get_logger

logger = get_logger(__name__)

# Characters allowed in a sanitized display filename (used only for metadata,
# never for the filesystem path).
_SAFE_FILENAME_RE = re.compile(r"[^\w\s.\-]")


def sanitize_filename(name: str) -> str:
    """Return a safe display filename.

    - Normalise unicode to NFKC
    - Strip null bytes and control characters
    - Replace unsafe characters with underscores
    - Collapse multiple consecutive dots/spaces
    - Limit length to 255 characters
    - Fall back to "unnamed" if the result is empty
    """
    # Normalise unicode
    name = unicodedata.normalize("NFKC", name)
    # Strip directory separators and null bytes
    name = name.replace("/", "_").replace("\\", "_").replace("\x00", "")
    # Replace anything that isn't alphanumeric, space, dot, dash, underscore
    name = _SAFE_FILENAME_RE.sub("_", name)
    # Collapse sequences of dots that could form relative path tricks
    while ".." in name:
        name = name.replace("..", ".")
    name = name.strip(". ")[:255]
    return name or "unnamed"


class LocalFileStorage:
    """Stores uploaded files on the local filesystem.

    The stored filename is always ``<document_id><extension>`` — the original
    filename is kept in metadata only and never touches the filesystem.
    """

    def __init__(self, storage_root: Path) -> None:
        self._root = storage_root.resolve()
        self._root.mkdir(parents=True, exist_ok=True)
        logger.info("storage.init", storage_root=str(self._root))

    @property
    def root(self) -> Path:
        return self._root

    def store(
        self,
        document_id: str,
        extension: str,
        data: bytes,
    ) -> Path:
        """Persist *data* and return the absolute storage path.

        The path is ``<root>/<document_id><extension>``.
        ``document_id`` is a UUID produced internally — not supplied by clients.
        """
        if not extension.startswith("."):
            extension = f".{extension}"
        # Build path from trusted components only
        dest = self._root / f"{document_id}{extension}"
        dest.write_bytes(data)
        logger.info(
            "storage.stored",
            document_id=document_id,
            bytes=len(data),
        )
        return dest

    def delete(self, file_path: Path) -> bool:
        """Delete *file_path* if it exists and is inside the storage root.

        Returns True if deleted, False if the file did not exist.
        Raises ``PermissionError`` if the resolved path escapes the storage root.
        """
        resolved = file_path.resolve()
        # Safety: confirm path is inside the storage root (protects against symlinks)
        try:
            resolved.relative_to(self._root)
        except ValueError:
            raise PermissionError(
                f"Attempted to delete a file outside the storage root: {resolved}"
            )
        if not resolved.exists():
            return False
        resolved.unlink()
        logger.info("storage.deleted", path=str(resolved))
        return True
